services:
  rpsee:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./config.toml
        target: /etc/rpsee/config.toml
        read_only: true
        bind:
          create_host_path: false
      - rpsee-data:/data

volumes:
  rpsee-data:
